export default {
  container: 'px-[20px] mt-[24px] mb-[150px]',
  title: 'md:hidden mb-[20px] font-interSemibold text-[24px] text-[#101828]',
  header: 'flex flex-wrap gap-4 justify-between',
  tabs: 'min-w-[200px]',
  wrapper: 'flex gap-4 flex-wrap',
  selectInput: 'h-[42px] min-w-[260px] sm:min-w-[12em] w-max cursor-pointer',
  datePicker: 'w-[260px] flex items-center gap-[10px] h-[42px] px-[14px] border border-[#CCDCE8] rounded-lg font-interMedium text-[14px] text-[#585D69]',
  csv: 'h-[42px] px-[12px] flex items-center rounded-lg border border-[#CCDCE8] font-interMedium text-[14px] text-[#70747E]',
  surveyTable: 'md:max-w-[calc(100vw-276px)] overflow-x-auto bg-color-white',
  footer: 'w-[100%] flex flex-wrap gap-4 items-center justify-between mt-[24px]',
  dropdownWrapper: 'flex gap-[12px] items-center',
  show: 'font-interMedium text-[14px] text-[#282F3E]',
  dropdownLabel: 'flex items-center gap-[15px] h-[42px] px-[14px] border border-[#CCDCE8] rounded-lg font-interMedium text-[14px] text-[#585D69] cursor-pointer',
  dropdownItems: 'flex-col py-[8px] px-[14px] font-interMedium border border-[#CCDCE8] text-[14px] rounded-lg',
  dropdownItem: 'cursor-pointer p-[10px] rounded-lg',
  filterWrapper: 'mt-4 flex-none flex flex-col-reverse lg:flex-row flex-wrap',
  selectInputWrapper: 'flex-1 flex flex-col lg:flex-row flex-wrap gap-4',
  clear: 'flex items-center cursor-pointer hover:text-[#585D69] h-[42px] hover:bg-[#E7ECF2] px-3 rounded-lg w-fit mb-4',
  translate: '-translate-y-[38vh] lg:-translate-y-16',
  translateNone: '-translate-y-0',
  transition: 'ease-in-out duration-500 lg:duration-300',
  transitionOpacity: 'transition-opacity duration-500 ease-out',
  opacityNone: 'opacity-0 invisible',
  opacityFull: 'opacity-100 visible',
};
