export default {
  titleWrapper: 'h-[32px] mt-[32px] mb-[12px] flex items-center bg-[#E6EEF3] px-[10px] rounded',
  titleText: 'font-inter text-[14px] text-[#585D69] uppercase',
  feelWrapper: 'flex items-center justify-center h-[56px] w-[67px] bg-[#F0F3F6] border border-[#B3CBDC] rounded-lg',
  feel: 'text-[24px]',
  wrapper: 'flex items-center justify-center h-[56px] w-[67px] bg-color-white border border-[#B3CBDC] rounded-lg',
  detailsContainer: 'flex justify-end fixed top-0 bottom-0 left-0 right-0 bg-[#10182880] overflow-y-scroll z-10',
  detailsModal: 'h-fit w-[625px] bg-[#fff]',
  headerWrapper: 'sticky top-0 pt-[28px] pb-[12px] bg-color-white px-[18px]',
  iconWrapper: 'w-[590px] flex items-center justify-between',
  closeModalIcon: 'bg-[#E7E8EA] flex items-center justify-center h-[24px] w-[24px] rounded-full cursor-pointer',
  header: 'flex items-center justify-between mt-[35px]',
  headerTitle: 'font-interSemibold text-[24px]',
  status: 'max-w-fit px-[12px] py-[4px] rounded-full uppercase font-interSemibold text-[14px]',
  pending: 'bg-[#FFF3E2] text-[#F79009]',
  rejected: 'bg-[#FFEFEE] text-[#F04438]',
  approved: 'bg-[#E7F5EF] text-[#12B76A]',
  date: 'font-inter text-[16px] text-[#585D69]',
  categoryWrapper: 'flex items-center gap-[10px]',
  categoryImg: 'h-[60px]',
  categoryTitle: 'font-interMedium text-[16px] leading-[19.36px]',
  photosWrapper: 'flex gap-[12px] overflow-x-auto max-w-[calc(100vw-40px)]',
  photo: 'h-[143px] w-[187px] rounded-lg object-cover',
  info: 'font-inter text-[16px] text-[#282F3E] leading-[24px]',
  mapWrapper: 'h-[229px] mt-[8px] mb-[32px] rounded-lg',
  buttons: 'flex justify-between gap-[16px] mb-[52px] px-[18px]',
  acceptBtn: 'w-[100%]',
  declineBtn: 'w-[100%] bg-[#E7E8EA]',
  declineBtnText: 'text-[#F04438]',
  declineModalOverlay: 'flex justify-center items-center fixed top-0 bottom-0 left-0 right-0 bg-[#10182880] z-20',
  declineModal: 'w-[629px] bg-[#fff] rounded-2xl',
  declineHeader: 'flex items-center justify-between gap-3 min-h-[80px] px-[20px] bg-[#E7ECF2] rounded-t-2xl',
  declineHeaderText: 'font-interSemibold text-[24px] text-[#101828]',
  closeIcon: 'flex items-center justify-center min-h-[24px] min-w-[24px] bg-[#fff] rounded-full cursor-pointer',
  declineContent: 'px-[20px] mt-[20px] mb-[32px]',
  declineText: 'font-interMedium text-[16px] text-[#404653] mb-[8px]',
  text: 'ml-[8px]',
  textarea: 'w-[100%] p-[10px] font-interMedium text-[16px] border border-[#CCDCE8] rounded-lg',
  declineButtons: 'flex justify-end gap-[8px] mt-[20px]',
  cancelBtn: 'bg-[#E7E8EA]',
  cancelBtnText: 'text-[#404653]',
  yesDeclineBtn: 'bg-[#F04438]',
  yesDeclineBtnText: 'text-[#fff]',
  exportDropdown: 'font-inter text-[#0A52A1]',
  exportButton: 'cursor-pointer bg-[#E7EEF6] flex justify-between items-center px-[10px] py-[8px] border border-[#0A52A1] rounded-lg',
  exportButtonTitle: 'color-[#0a52a1] ml-[8px]',
  exportOptions: 'cursor-pointer ml-[-90px] w-[190px] shadow-[0_5px_40px_0_rgba(0,0,0,0.16)] z-10 px-[11px] py-[13px] rounded-lg bg-[#fff]',
  exportOption: 'text-[#282F3E] px-[13px] py-[11px] hover:bg-[#F0F3F6] flex items-center rounded-lg',
  exportOptionTitle: 'text-[16px] ml-[12px] font-inter',
  entryWrapper: 'bg-[#fff] px-[18px] py-[20px]',
  // sliderContainer: 'bg-[#10182880] fixed z-20 top-0 overflow-auto',
  sliderContainer: 'fixed top-0 right-0 bg-[#10182880] flex justify-center',
};
