export default {
  section: 'p-5 flex flex-col justify-center',
  backWrapper: 'mb-8 flex items-center gap-3 w-[100%] cursor-pointer',
  backTitle: 'text-base font-normal text-[#101828]',
  content: 'flex sm:flex-row flex-col gap-8',
  itemContainer: 'w-[100%]',
  itemHeader: 'flex gap-8',
  logoWrapper: 'bg-[#F0F3F6] rounded-xl p-6 flex items-center justify-center',
  logo: 'max-h-[100px] max-w-[100px]',
  title: 'text-2xl font-semibold text-[#101828]',
  infoWrapper: 'flex gap-8 items-center mt-[12px] md:mt-[24px]',
  separator: 'border-[1px] border-[#E7E8EA] h-[44px]',
  info: 'flex flex-col gap-2',
  infoHeading: 'text-sm font-semibold text-[#888c94]',
  infoData: 'text-base font-medium text-color-text',
  description: 'my-8',
  contactHeading: 'rounded bg-[#f0f3f6] mb-3 p-[6px] font-semibold text-sm text-[#585d69]',
  website: 'flex items-center gap-2 max-w-fit text-base font-medium text-color-text',
  contactWrapper: 'flex flex-col gap-2',
  contactItem: 'flex gap-2 items-center',
  contactTitle: 'font-base text-sm text-[#888c94] font-normal',
  contactValue: 'font-base text-sm text-color-text font-normal',
  userContainer: 'flex flex-col min-w-[300px] p-5 rounded-lg border-[1px] border-[#E7E8EA]',
  userHeaderContainer: 'flex items-center flex flex-row justify-between pb-8',
  userHeader: 'font-semibold color-[#404653]',
  userItem: 'flex flex-row items-center',
  nameInitial: 'flex justify-center items-center bg-[#5486BD] text-color-white inline rounded-3xl mr-4 w-8 h-8',
  addButton: 'bg-[#F0F3F7] w-24',
  addButtonText: 'text-[#0A52A1]',
  userList: 'flex flex-col gap-8',
  deleteIcon: 'ml-auto cursor-pointer',
  modal: 'bg-[transparent] rounded-md',
  modalContent: 'p-8 bg-[white] rounded-md',
  modalActions: 'flex pt-4 gap-4 align-left',
  multiSelect: 'w-[360px]',
  orgContainer: 'mt-8',
  orgHeader: 'bg-[#F0F3F7] p-2 rounded-md my-4 text-[#585D69] font-semibold uppercase',
  orgContent: 'flex flex-row items-center border-[1px] border-[#E7E8EA] rounded-lg p-4',
  orgLogo: 'w-16',
  orgName: 'pl-8 text-[#0A52A1] font-semibold font-medium',
};
